config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  
  devise_for :customers, controllers: {
    registrations: 'customers/registrations'
  }
  devise_scope :customer do
    get 'addresses', to: 'customers/registrations#new_address'
    post 'addresses', to: 'customers/registrations#create_address'
  end

  devise_for :producers, controllers: {
    registrations: 'producers/registrations'
  }
  devise_scope :producer do
    get 'producer_addresses', to: 'producers/registrations#new_producer_address'
    post 'producer_addresses', to: 'producers/registrations#create_producer_address'
  end

  resources :items do
    post 'order', on: :member
    get :search, on: :collection
  end

  resources :producers do
    resources :profiles
  end
  resources :customers
  resources :cards, only: [:new, :create]
  root to: "items#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :producer, optional: true
  validates :postal_code, :city, :house_number, :building_name ,presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :family_name, :first_name, :kana_family_name, :kana_first_name, :birthday, presence: true
  has_one :address
  has_one :item_order
  has_one :card, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :producer, optional: true
  has_one :item_order
  has_one_attached :image
end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
               {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
               {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
               {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
               {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
               {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
               {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
               {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
               {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
               {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
               {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
               {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
               {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
               {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
               {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
               {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
               {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
              ]
end

app/models/producer.rb
class Producer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :family_name, :first_name, :kana_family_name, :kana_first_name, :birthday ,presence: true
  has_many :items
  has_one :producer_address
  has_one :profile
end

app/models/producer_address.rb
class ProducerAddress < ApplicationRecord
  belongs_to :producer, optional: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  validates :postal_code, :city, :house_number, :building_name ,presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :producer
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :kana_family_name, :kana_first_name, :birthday, :image])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def new
  end

  def create
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] 
    customer = Payjp::Customer.create(
    description: 'test', 
    card: params[:card_token] 
    )

    card = Card.new( 
      card_token: params[:card_token],
      customer_token: customer.id, 
      customer_id: current_customer.id 
    )

    if card.save
      redirect_to root_path
    else
      redirect_to "new"
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: :order

  
  def index
    @item = Item.order(created_at: :desc).limit(5)
  end

  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
  end

  def order

    redirect_to new_card_path and return unless current_customer.card.present?
    
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] 
    customer_token = current_customer.card.customer_token 
    Payjp::Charge.create(
      amount: @item.price, 
      customer: customer_token, 
      currency: 'jpy' 
    )
    ItemOrder.create(item_id: params[:id],customer_id: current_customer.id)

    redirect_to root_path
  end

  def search
    if params[:name].present?
      @items = Item.where('name LIKE ?', "%#{params[:name]}%" )
    else
      @items = Item.none
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :image).merge(producer_id: current_producer.id)
  end
  
  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController

  def show
   @producer = Producer.find(params[:id])
   @items = @producer.items
   @profile = @producer.profile
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.create(comment_params)
    if @profile.valid?
      redirect_to  producer_path(current_producer.id)
    else
      render :new
    end
  end

  def edit
    @profile = Profile.find(current_producer.profile.id)
  end

  def update
    @profile = Profile.find(current_producer.profile.id)
    @profile.update(comment_params)
    redirect_to root_path
  end

  private
  def comment_params
    params.require(:profile).permit(:producer_comment, :image).merge(producer_id: current_producer.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/cards/new.html.erb
<%= form_with  url: cards_path, id: 'charge-form', class: 'card-form',local: true do |f| %>
  <h1 class='info-input-haedline'>
    クレジットカード情報入力
  </h1>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">カード情報</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field 'number', class:"input-default", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
    <div class='available-card'>
      <%= image_tag 'card-visa.gif', class: 'card-logo'%>
      <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
      <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
      <%= image_tag 'card-amex.gif', class: 'card-logo'%>
   </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">有効期限</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-expiration-date-wrap'>
      <%= f.text_area :exp_month, class:"input-expiration-date", placeholder:"例)3" %>
      <p>月</p>
      <%= f.text_area :exp_year, class:"input-expiration-date", placeholder:"例)23" %>
      <p>年</p>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">セキュリティコード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :cvc, class:"input-default", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
  </div>
  <div class="card-btn">
    <%= f.submit "登録する" , class:"card-red-btn" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="items-sell-contents">
  
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>

  <%= form_with model: @item, local: true do |f| %>
 

   <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    
    
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明",rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    

    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    
    
    <div class="sell-btn-contents">
      <%= f.submit "更新する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>

  </div>
  <% end %>

</div>

app/views/items/index.html.erb
<div class="contents">

  <div class="search-form">
    <%= form_with url: search_items_path, method: :get, local: true do |f| %>
      <%= f.text_field :name %>
      <%= f.submit "検索する" %>
    <% end %>
  </div>

  <h2>Pick Up</h2>
  <div class="items">
    <% @item.each do |item| %>
      <div class="item">
        <div class="item-image">
          <%= link_to image_tag(item.image, size: '250x250'), item_path(item.id) %>
          <p><%= item.name %></p>
          <p><%= item.price %>円(税込)    <%= item.producer.producer_address.prefecture.name%>産</p>
        </div>
        <div class="item-info">
          <div class="bubble03">
           <%= item.description %> 
          </div>
          <div class="producer">
            <% if item.producer.profile.blank? %>
             <%= link_to image_tag('/assets/icon.jpg',size: '120x120'), producer_path(item.producer.id) %>
            <% else %>
             <%= link_to image_tag(item.producer.profile.image, size: '120x120'), producer_path(item.producer.id)  if item.producer.profile.image.attached? %>
            <% end %>
            <p><%= "#{item.producer.family_name}"+ "#{item.producer.first_name}" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="items-sell-contents">
  
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>

  <%= form_with model: @item, local: true do |f| %>
 

   <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    
    
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明",rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    

    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    
    
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>

  </div>
  <% end %>

</div>

app/views/items/search.html.erb
<div class="items">  
  <% @items.each do |item| %>
    <div class="item">
      <div class="item-image">
        <%= link_to image_tag(item.image, size: '250x250'), item_path(item.id) %>
        <p><%= item.name %></p>
        <p><%= item.price %>円(税込)</p>
      </div>
      <div class="item-info">
        <div class="bubble03">
         <%= item.description %> 
        </div>
        <div class="producer">
          <% if item.producer.profile.blank? %>
            <%= link_to image_tag('/assets/icon.jpg',size: '120x120'), producer_path(item.producer.id) %>
          <% else %>
            <%= link_to image_tag(item.producer.profile.image, size: '120x120'), producer_path(item.producer.id)  if item.producer.profile.image.attached? %>
          <% end %>
          <p><%= "#{item.producer.family_name}"+ "#{item.producer.first_name}" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/items/show.html.erb
<div class='item-show'>
  <div class='item-box'>
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag(@item.image, size: '400x300')%>
    </div>
    <div class='description-box'>
      <div class='producer'>
        <% if @item.producer.profile.blank? %>
          <%= link_to image_tag('/assets/icon.jpg',size: '150x150'), producer_path(@item.producer.id)%>
        <% else %>
          <%= link_to image_tag(@item.producer.profile.image, size: '150x150'), producer_path(@item.producer.id)%>
        <%end%>
        <p><%= @item.producer.family_name %><%= @item.producer.first_name %></p>
      </div>
      <div class='bubble02'>
      <%= @item.description %>
      </div>
    </div>
    <div class='item-price-box'>
      <span class="item-price">
        ¥<%= @item.price %>
      </span>
      <span class="item-postage">
        (税込) 送料込み
      </span>
    </div>
  </div>
    <div class='sell-btn-contents'>
    <% if producer_signed_in? && current_producer.id == @item.producer_id %>
      <%= link_to '商品の編集', edit_item_path(@item.id), method: :get, class: "item-red-btn" %>
      <p class='or-text'>or</p>
      <%= link_to '削除',item_path(@item.id) , method: :delete, class:'item-destroy' %>
    <% end %>
    <% if customer_signed_in? %>
      <%= link_to '購入する', order_item_path(@item.id), class:"item-red-btn", method: :post %>
    <% end %>
    </div>
  
   

</div>

app/views/items/update.html.erb
<div class="done-contents">
  <div class="done-message">
    <h1>更新が完了しました</h1>
  </div>
  <div class="done-btn">
    <%= link_to "マイページへ", "/producers/#{current_producer.id}", {class: "d-btn"}%>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="items-sell-contents">
  
  <div class="items-sell-main">

  <%= form_with model: @profile, url:producer_profile_path(current_producer.id),local: true do |f| %>

   <div class="img-upload">
      <div class="weight-bold-text">
        プロフィール画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    
    
    <div class="new-items">
      <div class="items-explain">
        <div class="weight-bold-text">
          コメント
        </div>
        <%= f.text_area :producer_comment, class:"items-text", id:"item-info", placeholder:"コメント",rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる',  producer_path(current_producer.id), class:"back-btn" %>
    </div>

  </div>
  <% end %>

</div>

app/views/profiles/new.html.erb
<div class="items-sell-contents">
  
  <div class="items-sell-main">

  <%= form_with model: @profile, url:producer_profiles_path(current_producer.id),local: true do |f| %>

   <div class="img-upload">
      <div class="weight-bold-text">
        プロフィール画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    
    
    <div class="new-items">
      <div class="items-explain">
        <div class="weight-bold-text">
          コメント
        </div>
        <%= f.text_area :producer_comment, class:"items-text", id:"item-info", placeholder:"コメント",rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる',  producer_path(current_producer.id), class:"back-btn" %>
    </div>

  </div>
  <% end %>

</div>