config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  
  devise_for :customers, controllers: {
    registrations: 'customers/registrations'
  }
  devise_scope :customer do
    get 'addresses', to: 'customers/registrations#new_address'
    post 'addresses', to: 'customers/registrations#create_address'
  end

  devise_for :producers, controllers: {
    registrations: 'producers/registrations'
  }
  devise_scope :producer do
    get 'producer_addresses', to: 'producers/registrations#new_producer_address'
    post 'producer_addresses', to: 'producers/registrations#create_producer_address'
  end

  resources :items do
    post 'order', on: :member
    get :search, on: :collection
  end

  resources :producers do
    resources :profiles
  end
  resources :customers
  resources :cards, only: [:new, :create]
  root to: "items#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :producer, optional: true
  validates :postal_code, :city, :house_number, :building_name ,presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :family_name, :first_name, :kana_family_name, :kana_first_name, :birthday, presence: true
  has_one :address
  has_one :item_order
  has_one :card, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :producer, optional: true
  has_one :item_order
  has_one_attached :image
end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
               {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
               {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
               {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
               {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
               {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
               {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
               {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
               {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
               {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
               {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
               {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
               {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
               {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
               {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
               {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
               {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
              ]
end

app/models/producer.rb
class Producer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :family_name, :first_name, :kana_family_name, :kana_first_name, :birthday ,presence: true
  has_many :items
  has_one :producer_address
  has_one :profile
end

app/models/producer_address.rb
class ProducerAddress < ApplicationRecord
  belongs_to :producer, optional: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  validates :postal_code, :city, :house_number, :building_name ,presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :producer
  has_one_attached :image
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def new
  end

  def create
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] 
    customer = Payjp::Customer.create(
    description: 'test', 
    card: params[:card_token] 
    )

    card = Card.new( 
      card_token: params[:card_token],
      customer_token: customer.id, 
      customer_id: current_customer.id 
    )

    if card.save
      redirect_to root_path
    else
      redirect_to "new"
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: :order

  
  def index
    @item = Item.order(created_at: :desc).limit(5)
  end

  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
  end

  def order

    redirect_to new_card_path and return unless current_customer.card.present?
    
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] 
    customer_token = current_customer.card.customer_token 
    Payjp::Charge.create(
      amount: @item.price, 
      customer: customer_token, 
      currency: 'jpy' 
    )
    ItemOrder.create(item_id: params[:id],customer_id: current_customer.id)

    redirect_to root_path
  end

  def search
    if params[:name].present?
      @items = Item.where('name LIKE ?', "%#{params[:name]}%" )
    else
      @items = Item.none
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :image).merge(producer_id: current_producer.id)
  end
  
  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.create(comment_params)
    if @profile.valid?
      redirect_to  producer_path(current_producer.id)
    else
      render :new
    end
  end

  def edit
    @profile = Profile.find(current_producer.profile.id)
  end

  def update
    @profile = Profile.find(current_producer.profile.id)
    @profile.update(comment_params)
    redirect_to root_path
  end

  private
  def comment_params
    params.require(:profile).permit(:producer_comment, :image).merge(producer_id: current_producer.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DirectVegetables</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.pay.jp/" , type="text/javascript"></script>
  </head>
  <body>
  <div class='container'>
    <div class="header">
      <div class="title">
       <h1><span class="c1">D</span>-vege</h1>
       <p>農家から直接野菜を購入しよう！</p>
       <div class="btn">
         <ul>
          <% if producer_signed_in? && !current_page?("/producers/#{current_producer.id}") %>
           <li class="left"><%= link_to '商品を投稿する', new_item_path %>
           <li class="right"><%= link_to 'ログアウト', destroy_producer_session_path, method: :delete %>
           <li class="center"><%= link_to 'マイページ', "/producers/#{current_producer.id}" %>
          <% elsif producer_signed_in? %>
           <li class="left"><%= link_to '商品を投稿する', new_item_path %>
           <li class="right"><%= link_to 'ログアウト', destroy_producer_session_path, method: :delete %>
          <% elsif customer_signed_in? %> 
            <li class="center"><%= link_to '購入履歴', customer_path(current_customer.id) %>
            <li class="right"><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %>
          <% else %>
           <li class="left"><%= link_to 'ログイン', new_customer_session_path %></li>
           <li class="right"><%= link_to '新規登録', new_customer_registration_path %></li>
          <% end %>
         </ul>
        </div>
      </div>
    </div>
    <%= yield %>

    <div class="footer">
     <% if customer_signed_in? && current_customer.card == nil && !current_page?("/cards/new")%>
       <%= link_to 'クレジットカードを登録する', new_card_path %>
     <% elsif !customer_signed_in? && !producer_signed_in? && !current_page?(root_path) %>
       <%= link_to 'トップページへ', root_path %><br>
       <%= link_to '生産者の方はこちら', new_producer_session_path %>
     <% elsif customer_signed_in? && !current_page?(root_path) %>
       <%= link_to 'トップページへ', root_path %>
     <% elsif producer_signed_in? && !current_page?(root_path) %>
       <%= link_to 'トップページへ', root_path %>
     <% elsif !customer_signed_in? && !producer_signed_in? %>
       <%= link_to '生産者の方はこちら', new_producer_session_path %>
     <% end %>
    </div>
  </div>
  </body>
</html>